R CMD BATCH CI_Ind_1.R &
R CMD BATCH CI_Ind_2.R &
R CMD BATCH CI_Ind_3.R &
R CMD BATCH CI_Ind_4.R &
R CMD BATCH CI_Ind_5.R &
R CMD BATCH CI_Ind_6.R &
R CMD BATCH CI_Ind_7.R &
R CMD BATCH CI_Ind_8.R &

